spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://db:3306/testdb?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=Asia/Seoul}
    username: ${SPRING_DATASOURCE_USERNAME:test}
    password: ${SPRING_DATASOURCE_PASSWORD:1234}
    driver-class-name: com.mysql.cj.jdbc.Driver