spring:
  datasource:
    url: jdbc:mysql://db:3306/testdb?allowPublicKeyRetrieval=true&useSSL=true&serverTimezone=Asia/Seoul
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver